[development]
address = "0.0.0.0"
port = 8000
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
# can't be specified in any environment otherwise it validates for dev
# use ROCKET_TLS to specify
# tls = { key = "/path/to/pem.key", certs="/path/to/pem.crt" }
port = 8443
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
limits = { forms = 32768 }
